import { Q6 } from "./q6";
import { LanguageAbility } from "app/models/languageAbility";
import { Apprenticeship } from "app/models/apprenticeship";
import { Education } from "app/models/education";
import { Employee } from "app/models/employee";
import { EmploymentRecord } from "app/models/employmentRecord";
import { FamilyDetail } from "app/models/familyDetail";

export class PersonalInformation {
    citizenID: string;
    titleTH: string;
    fNameTH: string;
    lNameTH: string;
    fNameEN: string;
    lNameEN: string;
    address: string;
    email: string;
    phoneNumber: string;
    dateOfBirth: Date;
    placeOfBirth: string;
    weight: number;
    heigth: number;
    nationality: string;
    race: string;
    religion: string;
    profNo: string;
    militaryStatus: string;
    maritalStatus: string ;
    apprenticeships: Apprenticeship[];
    educations: Education[];
    employmentRecords: EmploymentRecord[];
    familyDetails: FamilyDetail[];
    emergencyContact: string;
    languageAbilities: LanguageAbility[];
    toeicScore: number;
    toeicYear: number;
    toeflScore: number;
    toeflYear: number;
    word: number;
    excel: number;
    powerponumber: number;
    driveCar: boolean;
    ownCar: boolean;
    driveLicenseCar: string;
    rideMotocycle: boolean;
    ownMotocycle: boolean;
    driveLicenseMotocycle: boolean;
    hobby: string;
    q1: boolean;
    q2: boolean;
    q3: boolean;
    q4: boolean;
    q5: boolean;
    q6: Q6[];
}