import { Q6 } from "./q6";
import { LanguageAbility } from "app/models/languageAbility";
import { Apprenticeship } from "app/models/apprenticeship";
import { Education } from "app/models/education";
import { Employee } from "app/models/employee";
import { EmploymentRecord } from "app/models/employmentRecord";
import { FamilyDetail } from "app/models/familyDetail";

export class PersonalInformation {
    citizenID: string;
    titleTH: string;
    fNameTH: string;
    lNameTH: string;
    fNameEN: string;
    lNameEN: string;
    address: string;
    email: string;
    telephone: string;
    dateOfBirth: Date;
    placeOfBirth: string;
    weight: number;
    height: number;
    nationality: string;
    race: string;
    religion: string;
    profNo: string;
    militaryStatus: string;
    maritalStatus: string ;
    apprenticeships: Apprenticeship[];
    educations: Education[];
    employmentRecords: EmploymentRecord[];
    familyDetails: FamilyDetail[];
    emergencyContact: string;
    languageAbilities: LanguageAbility[];
    toeicScore: number;
    toeicYear: number;
    toeflScore: number;
    toeflYear: number;
    word: number;
    excel: number;
    powerPoint: number;
    driveCar: string;
    ownCar: string;
    driveLicenseCar: string;
    rideMotocycle: string;
    ownMotocycle: string;
    driveLicenseMotocycle: string;
    hobby: string;
    q1: string;
    q2: string;
    q3: string;
    q4: string;
    q5: string;
    q6: Q6[];
}